config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :employees
  devise_for :users, path: 'users', controllers: { registrations: 'users/registrations',
                                                   sessions: 'users/sessions' }
  devise_for :companies, path: 'companies', controllers: { registrations: 'companies/registrations',
                                                           sessions: 'companies/sessions' }
  namespace :employees do
    resources :sessions, only: %i[new create] do
      delete 'destroy', on: :collection
    end
  end
  resources :attendances, only: %i[destroy]
  resources :companies, only: %i[index show]
  resources :categories
  resources :products
  resources :suppliers
  resources :transaktions, only: %i[index show new create]
  resources :menus do
    get 'by_category', to: 'menus#by_category', default: :json, on: :collection
  end
  resources :boards, except: :show do
    resources :orders
    get 'positions', to: 'boards#positions', on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :bigint(8)        not null, primary key
#  name        :string
#  description :string
#  company_id  :bigint(8)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :menus, dependent: :destroy
  belongs_to :company

  validates :name, presence: true, uniqueness: { scope: :company_id }
  validates :description, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_company!
  before_action :authenticate_admin!
  before_action :find_category, except: %i[index new create]

  def index
    @categories = current_company.categories
    respond_to do |format|
      format.html
      format.json { render json: CategoryDatatable.new(params, current_company: current_company) }
    end
  end

  def show; end

  def new
    @category = current_company.categories.new
  end

  def create
    @category = current_company.categories.new(category_params)
    if @category.save
      flash[:notice] = 'Categoría creada exitosamente'
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Categoría actualizada exitosamente'
      redirect_to category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    @category.destroy!
    flash[:notice] = 'Categoría eliminada exitosamente'
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

  def find_category
    @category = current_company.categories.find(params[:id])
  end
end

app/views/categories/_actions.html.erb
<%= link_to "Ver", category_path(category) %> |
<%= link_to "Editar", edit_category_path(category) %> |
<%= link_to "Borrar", category_path(category), method: :delete, data: { confirm: '¿Borrar categoría?'} %>

app/views/categories/_categories.html.erb
<div class="btn-group btn-group-lg" role="group" aria-label="categories">
  <% categories.each do |category| %>
    <%= link_to category.name, by_category_menus_path(category_id: category.id, board_id: board.id),
                               class: 'btn btn-secondary', remote: true  %>
  <% end %>
</div>

app/views/categories/_category.html.erb
<tr id="category-<%= category.id %>">
  <td><%= category.id %></td>
  <td><%= category.name.titleize %></td>
  <td><%= category.description.capitalize %></td>
  <td><%= category.products.count %></td>
  <td><%= link_to 'Ver', category_path(category) %> -
      <%= link_to 'Editar', edit_category_path(category) %> -
      <%= link_to 'Eliminar', category_path(category), method: :delete, data: { confirm: "Si elimina esta categoría, tambien eliminas #{category.products.count} productos. Estas seguro?" } %></td>
</tr>

app/views/categories/_form.html.erb
<div class="container">
  <div class="categories">
    <h1 class = "text-center"><%= action %> Categoría</h1>
    <%= form_for(@category) do |category| %>
      <% if @category.errors.any? %>
          <div id="errors_explanation">
            <h2><%=pluralize(@category.errors.count,"error")%> No se pudo crear categoria por los siguientes errores:</h2>
            <ul>
            <% @category.errors.full_messages.each do |message| %>
              <li><%=message %></li>
            <% end %>
            </ul>
          </div>
      <% end %>

      <div class="row justify-content-center">
        <div class="col-md-6">
          <div class="form-group">
            <%= category.label :name %>
            <%= category.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= category.label :description %>
            <%= category.text_area :description, class: "form-control" %>
          </div>
          <div class="actions d-flex justify-content-end">
            <%= link_to 'Cancelar', categories_path, class: 'btn btn-secondary' %>
            <%= category.submit 'Guardar', class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<%= render 'form', action: "Editar" %>

app/views/categories/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="d-flex justify-content-between align-items-center">
        <h1 class="text-center">Categorías</h1>
        <%= link_to 'Crear Categoría', new_category_path, class: 'btn btn-primary float-right' %>
      </div>
    </div>
  </div>
  <div class="table-responsive">
    <table class='table' id="categories-datatable" data-source="<%= categories_path(format: :json) %>">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Description</th>
          <th>Products</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody></tbody>
    </table>
  </div>
</div>

<script type="text/javascript">
  new CategoryTable();
</script>

app/views/categories/new.html.erb
<%= render 'form', action: "Nueva" %>

app/views/categories/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4"><%= @category.name.titleize %></h1>
    <p class="lead"><%= @category.description.capitalize %></p>
    <%= link_to 'Categorías', categories_path, class: 'btn btn-primary' %>
    <%= link_to 'Crear categoría', new_category_path, class: 'btn btn-success' %>
  </div>
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="d-flex justify-content-between align-items-center">
        <h3 class="text-center">Productos</h3>
        <%= link_to 'Crear producto', new_product_path, class: 'btn btn-primary float-right' %>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th>Precio unitario</th>
            <th>Descripción</th>
            <th>Marca</th>
            <th>Categoria</th>
            <th>Proveedor</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% if @category.products.empty? %>
            <tr><td class='text-center'>No hay productos creadas aun</td></tr>
          <% else %>
            <%= render @category.products %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>  
</div>